/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenghitunghari;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Year;
import java.time.ZoneId;
import java.time.format.TextStyle;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PenghitungHariFrame extends javax.swing.JFrame {

    private Object tahunkabisat;
    private boolean isKasbisat;

    /**
     * Creates new form PenghitungHariFrame
     */
    public PenghitungHariFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbbulan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tanggalakhir = new de.wannawork.jcalendar.JCalendarComboBox();
        spinertahun = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        tanggalawal = new de.wannawork.jcalendar.JCalendarComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jumlahhari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        haripertama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        thnkabisat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hariterakhir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        selisihhari = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        hitung = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(3000, 1900, 3000, 1));
        jSpinner1.setPreferredSize(new java.awt.Dimension(165, 26));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aplikasi Penghitung Hari", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Tahun :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 118, 0, 0);
        jPanel5.add(jLabel2, gridBagConstraints);

        jLabel4.setText("Bulan :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 124, 0, 0);
        jPanel5.add(jLabel4, gridBagConstraints);

        cbbbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli ", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbbbulan.setPreferredSize(new java.awt.Dimension(200, 26));
        cbbbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbbulanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 77, 0, 90);
        jPanel5.add(cbbbulan, gridBagConstraints);

        jLabel6.setText("Tanggal Akhir :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 118, 16, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        tanggalakhir.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tanggalakhirAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 77, 16, 90);
        jPanel5.add(tanggalakhir, gridBagConstraints);

        spinertahun.setModel(new javax.swing.SpinnerNumberModel(2024, 1900, 2100, 1));
        spinertahun.setPreferredSize(new java.awt.Dimension(165, 26));
        spinertahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinertahunStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 133;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 77, 0, 90);
        jPanel5.add(spinertahun, gridBagConstraints);

        jLabel8.setText("Tanggal Awal :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 118, 16, 0);
        jPanel5.add(jLabel8, gridBagConstraints);

        tanggalawal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tanggalawalAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 77, 16, 90);
        jPanel5.add(tanggalawal, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Jumlah Hari   :");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jumlahhari.setPreferredSize(new java.awt.Dimension(300, 26));
        jPanel2.add(jumlahhari, new java.awt.GridBagConstraints());

        jLabel1.setText("Hari Pertama :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel1, gridBagConstraints);

        haripertama.setPreferredSize(new java.awt.Dimension(300, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(haripertama, gridBagConstraints);

        jLabel5.setText("Tahun Kabisat :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel5, gridBagConstraints);

        thnkabisat.setPreferredSize(new java.awt.Dimension(300, 26));
        thnkabisat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thnkabisatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel2.add(thnkabisat, gridBagConstraints);

        jLabel7.setText("Hari Terakhir :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel7, gridBagConstraints);

        hariterakhir.setPreferredSize(new java.awt.Dimension(300, 26));
        hariterakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariterakhirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel2.add(hariterakhir, gridBagConstraints);

        jLabel9.setText("Selisih Hari :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel9, gridBagConstraints);

        selisihhari.setPreferredSize(new java.awt.Dimension(300, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel2.add(selisihhari, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel3.add(hitung, new java.awt.GridBagConstraints());

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus, new java.awt.GridBagConstraints());

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel3.add(keluar, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
           int tahun = (Integer) spinertahun.getValue();
           String bulanString = (String) cbbbulan.getSelectedItem();
           int bulan = cbbbulan.getSelectedIndex() + 1; 
           int jumlahHari;
           
           try {
            // Validasi jumlah hari untuk bulan
            if (bulan == 2) { // Februari
                jumlahHari = ((tahun % 4 == 0 && tahun % 100 != 0) || (tahun % 400 == 0)) ? 29 : 28;
            } else if (bulan == 4 || bulan == 6 || bulan == 9 || bulan == 11) { // Bulan dengan 30 hari
                jumlahHari = 30;
            } else {
                jumlahHari = 31; // Bulan lainnya
            }

            // Menentukan tanggal pertama dan terakhir
            LocalDate tanggalPertama = LocalDate.of(tahun, bulan, 1);
            LocalDate tanggalTerakhir = LocalDate.of(tahun, bulan, jumlahHari);

            // Menentukan nama hari pertama dan terakhir
            String hariPertama = tanggalPertama.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH); // Nama hari dalam bahasa Inggris
            String hariTerakhir = tanggalTerakhir.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH);

            jumlahhari.setText(String.valueOf(jumlahHari));
            haripertama.setText(hariPertama);
            hariterakhir.setText(hariTerakhir);
            
            boolean isKabisat = (tahun % 4 == 0 && tahun % 100 != 0) || (tahun % 400 == 0);
            thnkabisat.setText(isKabisat ? "Ya" : "Tidak");

            LocalDate tanggalAwal = tanggalawal.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate tanggalAkhir = tanggalakhir.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            if (tanggalAkhir.isBefore(tanggalAwal)) {
                JOptionPane.showMessageDialog(this, "Tanggal akhir harus setelah tanggal awal.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            long selisihHari = ChronoUnit.DAYS.between(tanggalAwal, tanggalAkhir);
            selisihhari.setText(String.valueOf(selisihHari));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        jumlahhari.setText("");
        haripertama.setText("");
        hariterakhir.setText("");
        thnkabisat.setText("");
        selisihhari.setText("");
        cbbbulan.setSelectedIndex(0);
        spinertahun.setValue(LocalDate.now().getYear());
        tanggalawal.setDate(java.sql.Date.valueOf(LocalDate.now()));
        tanggalakhir.setDate(java.sql.Date.valueOf(LocalDate.now()));
    }//GEN-LAST:event_hapusActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // Membuat Event untuk koonfirmasi apakah yakin akan keluar aplikasi
        int pilihan = JOptionPane.showConfirmDialog(
            null,
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi Keluar",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        if (pilihan == JOptionPane.YES_OPTION) {
            System.exit(0);  // Keluar dari aplikasi jika pengguna memilih "Ya"
        } else if (pilihan == JOptionPane.NO_OPTION) {
            // Tetap di aplikasi jika pengguna memilih "Tidak"
        } else if (pilihan == JOptionPane.CANCEL_OPTION) {
            // Tetap di aplikasi jika pengguna memilih "Batal"
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1StateChanged

    private void spinertahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinertahunStateChanged

    }//GEN-LAST:event_spinertahunStateChanged

    private void cbbbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbbulanActionPerformed

    }//GEN-LAST:event_cbbbulanActionPerformed

    private void tanggalakhirAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tanggalakhirAncestorAdded

    }//GEN-LAST:event_tanggalakhirAncestorAdded

    private void tanggalawalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tanggalawalAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalawalAncestorAdded

    private void thnkabisatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thnkabisatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thnkabisatActionPerformed

    private void hariterakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariterakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hariterakhirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungHariFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbbulan;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField haripertama;
    private javax.swing.JTextField hariterakhir;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jumlahhari;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField selisihhari;
    private javax.swing.JSpinner spinertahun;
    private de.wannawork.jcalendar.JCalendarComboBox tanggalakhir;
    private de.wannawork.jcalendar.JCalendarComboBox tanggalawal;
    private javax.swing.JTextField thnkabisat;
    // End of variables declaration//GEN-END:variables

}
